# Generated by Django 5.0.6 on 2024-06-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=50)),
                ('pub_on', models.DateTimeField(auto_now=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
