# Generated by Django 5.0.6 on 2024-06-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_pub_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='b_content',
            field=models.TextField(default=''),
        ),
    ]
