# Generated by Django 5.0.6 on 2024-06-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_b_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author_name',
            new_name='a_name',
        ),
    ]
