# Generated by Django 5.0.6 on 2024-07-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_b_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='b_image',
            field=models.ImageField(default='default.jpg', upload_to='blog_image'),
        ),
    ]
